name: 'Release and Update Chart'
description: 'This action is intended to run on PR merge. It performs a semantic-release, then creates a PR into a helm chart repository with an updated appVersion, using the same PR title and body as the PR that triggered the workflow'
inputs:
  token:
    description: 'Github token to use, this should be a PAT so that it can trigger workflows on the destination helm repository'
    required: true
  release-config:
    description: 'semantic-release release configuration to use'
    required: false
    default: '@unsupervised/release-config-general'
  helm-repo:
    description: 'The helm chart git repo to update'
    required: false
    default: '${{ github.repository_owner }}/chart-${{ github.event.repository.name }}'
  sentry-auth-token:
    description: 'Sentry auth token to facilitate sentry releases'
    required: false
    default: false
  sentry-org-slug:
    description: 'Sentry org name to facilitate sentry releases'
    required: false
    default: false
  sentry-project-name:
    description: 'Sentry project to update with release info'
    required: false
    default: false
  helm-repo-branch:
    description: 'The helm chart git repo to branch from and PR into'
    required: false
    default: alpha
  path-to-chart:
    description: 'The path to the helm chart in the helm git repo'
    required: false
    default: chart
  labels:
    description: 'Labels to apply to the PR. Should be a comma separated string'
    required: false
    default: automerge
  delete-branch:
    description: 'Delete PR branch after merge'
    required: false
    default: true
  branch-prefix:
    description: 'The prefix for the name of the feature branch'
    required: false
    default: 'automated-code-release-'
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - name: Release
      id: release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extends: ${{ inputs.release-config }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - if: steps.release.outputs.new_release_published == 'true'
      name: Checkout helm chart
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.helm-repo }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.helm-repo-branch }}
    - if: steps.release.outputs.new_release_published == 'true'
      name: Update appVersion
      shell: bash
      run: |
        sed -i "0,/appVersion:.*/s//appVersion: \"${{ steps.release.outputs.new_release_version }}\"/g" ${{ inputs.path-to-chart }}/Chart.yaml
    - if: steps.release.outputs.new_release_published == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.token }}
        title: ${{ github.event.pull_request.title }}
        body: '${{ github.event.pull_request.body }}<br />Automated changes triggered by [pull request](${{ github.event.pull_request._links.html.href }})'
        commit-message: ${{ github.event.pull_request.title }}
        branch: '${{ inputs.branch-prefix }}${{ steps.release.outputs.new_release_version }}'
        delete-branch: ${{ inputs.delete-branch }}
        labels: ${{ inputs.labels }}
    - if: ${{ (steps.release.outputs.new_release_published == 'true') && (inputs.sentry-auth-token != 'false') }}
      name: sentry release
      uses: getsentry/action-release@v1.1.6
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}
        SENTRY_ORG: ${{ inputs.sentry-org-slug }}
        SENTRY_PROJECT: ${{ inputs.sentry-project-name }}
      with:
        version: ${{ steps.release.outputs.new_release_version }}
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true
