name: Validate pull request
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint action.yaml
        with:
          config_data: "{extends: default, rules: {line-length: disable}}"
